### ISSUE TITLE
No such package mariadb-client-libs

### ISSUE THREAD

**Issue by rickard-von-essen** [docker-in-aws/docker-in-aws#1]
```shell
/ # apk add mariadb-client-libs
ERROR: unsatisfiable constraints:
  mariadb-client-libs (missing):
    required by: world[mariadb-client-libs]
```

**Comment by rickard-von-essen** [comment]
Code was removed.

**Comment by xueruini** [comment]
which pkg to install if I want to use the files in `mariadb-client-libs`?

**Comment by mixja** [comment]
The package is now called mariadb-client - see https://github.com/docker-in-aws/docker-in-aws/blob/master/ch2/todobackend/Dockerfile#L32

**Comment by xueruini** [comment]
I found the two so files in `mariadb-client-libs` are not included in `mariadb-client`.

https://pkgs.alpinelinux.org/contents?branch=v3.7&name=mariadb-client-libs&arch=x86_64&repo=main
![image](https://user-images.githubusercontent.com/1863/44846386-c83d8100-ac82-11e8-8559-2ff2198ea67c.png)
![image](https://user-images.githubusercontent.com/1863/44846481-05a20e80-ac83-11e8-92c3-2668194b2ebe.png)

https://pkgs.alpinelinux.org/contents?branch=v3.8&name=mariadb-client&arch=x86_64&repo=main
![image](https://user-images.githubusercontent.com/1863/44846448-f58a2f00-ac82-11e8-814c-7a90f2a1f97c.png)

**Comment by mixja** [comment]
Can you advise if this is causing an issue?

**Comment by xueruini** [comment]
> Can you advise if this is causing an issue?

I am using python mysqlclient and it expects the so files.

**Comment by mixja** [comment]
Hi

Just to clarify, can you confirm if this is affecting your ability to progress through the [Packt Docker on Amazon Web Services book](https://www.packtpub.com/virtualization-and-cloud/docker-amazon-web-services)?

Thanks
Justin

**Comment by xueruini** [comment]
> Just to clarify, can you confirm if this is affecting your ability to progress through the [Packt Docker on Amazon Web Services book](https://www.packtpub.com/virtualization-and-cloud/docker-amazon-web-services)?

To be honest, I am not reading this book. I came to this post via google....

**Comment by mhenrixon** [comment]
Using ruby but same problem `mariadb-client` does not work unfortunately.

**Comment by mhenrixon** [comment]
Looks like using `mariadb-dev` works!

**Comment by tinypulse-juanma** [comment]
but mariadb-dev is like 110mbs.. not a good approach for docker..

**Comment by rickard-von-essen** [comment]
@tinypulse-juanma seems like an unrelated (and incorrect) comment.
